using AdventOfCode.Tools.Pathfinding;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;

namespace AoCommonTest
{
    [TestClass]
    public class AStarTest
    {
        static int[] pathColors;

        [AssemblyInitialize]
        public static void Setup(TestContext testContext)
        {
            pathColors = new Color[] { 
                Color.Red,
                Color.FromArgb(255, 55, 55)
            }.Select(x => x.ToArgb()).ToArray();
        }

        //Testing A* MAze Solving with maze generated by
        //https://keesiemeijer.github.io/maze-generator/


        /// <summary>
        /// Tests, whether A* finds the same path as the solution
        /// </summary>
        /// <param name="nodes">The Nodes provided in the Maze</param>
        /// <param name="connections">The Connections of the nodes</param>
        /// <param name="solution">The nondes in the solution</param>
        /// <remarks>The node order in the solution is not accounted for.</remarks>
        [TestMethod]
        [DynamicData(nameof(GetTestMazes), DynamicDataSourceType.Method)]
        public void MazeSolveTest(List<BaseNode> nodes, List<BaseNodeConnection> connections, List<BaseNode> solution)
        {
            AStar aStar = new AStar(connections);
            BaseNode start = nodes.First();
            BaseNode last = nodes.Last();
            BaseNode[] path = aStar.GetPath(start, last);

            var difference1 = path.Except(solution);
            var difference2 = solution.Except(path);

            Trace.WriteLine("Nodes: " + string.Join(" ", nodes.Select(x => x.ToString())));

            Trace.WriteLine("Expected Path: " + string.Join(" ", solution.Select(x => x.ToString())));
            Trace.WriteLine("Found Path: " + string.Join(" ", path.Select(x => x.ToString())));
            Trace.WriteLine("Difference path-solution: " + string.Join(" ", difference1.Select(x => x.ToString())));
            Trace.WriteLine("Difference solution-path: " + string.Join(" ", difference2.Select(x => x.ToString())));


            Assert.AreEqual(solution.Count, path.Length);
            Assert.AreEqual(0, difference1.Count());
            Assert.AreEqual(0, difference2.Count());
        }

        private static IEnumerable<object[]> GetTestMazes()
        {
            foreach (string maze in Directory.GetFiles(@"..\..\Data\Mazes\non-perfect", "*.bmp"))
            {
                List<BaseNode> nodes = new List<BaseNode>();
                List<BaseNode> solution = new List<BaseNode>();
                List<BaseNodeConnection> connections = new List<BaseNodeConnection>();
                using (Bitmap mazeMap = new Bitmap(maze))
                {
                    for (int y = 0; y < mazeMap.Height; ++y)
                        for (int x = 0; x < mazeMap.Width; ++x)
                        {
                            Color pixelColor = mazeMap.GetPixel(x, y);
                            if (pixelColor.ToArgb() == Color.Black.ToArgb()) continue;
                            BaseNode node = new BaseNode(x, y);
                            nodes.Add(node);
                            if (pathColors.Contains(pixelColor.ToArgb())) solution.Add(node);
                            BaseNode left = nodes.SingleOrDefault(testNode => testNode.Y == y && testNode.X == x - 1);
                            BaseNode top = nodes.SingleOrDefault(testNode => testNode.Y - 1 == y && testNode.X == x);
                            if (left != null)
                                connections.Add(new BaseNodeConnection(left, node));
                            if (top != null)
                                connections.Add(new BaseNodeConnection(top, node));
                        }
                }

                yield return new object[] { nodes, connections, solution };
            }
        }
    }
}
